[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]
rapid-router = {editable = true, path = "."}

[dev-packages]
django-selenium-clean = "==0.3.3"
django-test-migrations = "==1.2.0"
selenium = "==3.141.0"
pytest-django = "==4.5.2"
pytest = "==7.*"
pytest-xdist = "*"
pytest-order = "*"
codeforlife-portal = "*"
django-import-export = "*"
importlib-metadata = "<5" # Using version 5 causes an issue when trying to run pytest. Not sure why, linked to: https://stackoverflow.com/questions/73929564/entrypoints-object-has-no-attribute-get-digital-ocean

[requires]
python_version = "3.7"
