[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]
cfl-common = ">=8.0.0"
ipython = "*"
rapid-router = {path = ".", editable = true}

[dev-packages]
black = "*"
codeforlife-portal = ">=8.0.0"
django-selenium-clean = "==1.0.1"
django-test-migrations = "==1.4.0"
importlib-metadata = "<5" # Using version 5 causes an issue when trying to run pytest. Not sure why, linked to: https://stackoverflow.com/questions/73929564/entrypoints-object-has-no-attribute-get-digital-ocean
isort = "*"
pytest = "==8.*"
pytest-django = "==4.8.0"
pytest-order = "*"
pytest-xdist = "*"
selenium = "==4.9.0"

[requires]
python_version = "3.12"
